# Generated by Django 4.2.9 on 2024-02-07 20:02

import apps.estates.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bedrooms', 'Bedrooms'), ('toilets', 'Toilets'), ('bathroom', 'Bathroom'), ('environments', 'Environments'), ('flats', 'Flats'), ('garage', 'Garage'), ('flats', 'Flats')], max_length=20)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=600, upload_to=apps.estates.models.estates_directory)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(blank=True, default=uuid.uuid4, max_length=126, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('type', models.CharField(choices=[('casa', 'Casa'), ('casa_duplex', 'Casa_duplex'), ('casa_triplex', 'Casa_triplex'), ('departamento', 'Departamento'), ('monoambiente', 'Monoambiente'), ('departamento_piso', 'Departamento_piso'), ('departamento_penthouse', 'Departamento_penthouse'), ('departamento_semipiso', 'Departamento_semipiso'), ('departamento_duplex', 'Departamento_duplex'), ('departamento_triplex', 'Departamento_triplex'), ('ph', 'Ph'), ('oficina', 'Oficina'), ('consultorio', 'Consultorio'), ('quinta', 'Quinta'), ('chacra', 'Chara'), ('galpon', 'Galpon'), ('deposito', 'Deposito'), ('campo', 'Campo'), ('hotel', 'Hotel'), ('fondo de comercio', 'Fondo de comercio'), ('edificio', 'Edificio'), ('cochera', 'Cochera'), ('otros', 'Otros')], default='otros', max_length=85)),
                ('operation', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('auction', 'Auction'), ('others', 'Others')], default='others', max_length=85)),
                ('title', models.CharField(max_length=256)),
                ('num_flat', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('expenses', models.IntegerField(blank=True, null=True)),
                ('currency_price', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('OTHER', 'OTHER')], default='ARS', max_length=10)),
                ('currency_expenses', models.CharField(blank=True, choices=[('ARS', 'ARS'), ('USD', 'USD'), ('OTHER', 'OTHER')], default=None, max_length=10, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.estates.models.estates_directory_video)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('province', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('promotion', models.BooleanField(default=False)),
                ('street_number', models.IntegerField()),
                ('state', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=35)),
                ('antiquity', models.IntegerField(default=0)),
                ('id_department', models.CharField(blank=True, max_length=5, null=True)),
                ('terrain_sup', models.IntegerField(blank=True, null=True)),
                ('cover_sup', models.IntegerField(blank=True, null=True)),
                ('total_sup', models.IntegerField(blank=True, null=True)),
                ('financing', models.BooleanField(default=False)),
                ('services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('sewer', 'Sewer'), ('care', 'Care'), ('maintenance', 'Maintenance')], max_length=85, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='estates.feature')),
                ('images', models.ManyToManyField(related_name='property_images', to='estates.image')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=256)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_view_count', to='estates.property')),
            ],
        ),
    ]
