# Generated by Django 4.2.9 on 2024-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='antiquity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('casa', 'Casa'), ('casa_duplex', 'Casa_duplex'), ('casa_triplex', 'Casa_triplex'), ('departamento', 'Departamento'), ('monoambiente', 'Monoambiente'), ('departamento piso', 'Departamento piso'), ('departamento penthouse', 'Departamento penthouse'), ('departamento semipiso', 'Departamento semipiso'), ('departamento duplex', 'Departamento duplex'), ('departamento triplex', 'Departamento triplex'), ('ph', 'Ph'), ('oficina', 'Oficina'), ('consultorio', 'Consultorio'), ('quinta', 'Quinta'), ('chacra', 'Chara'), ('galpon', 'Galpon'), ('deposito', 'Deposito'), ('campo', 'Campo'), ('hotel', 'Hotel'), ('fondo de comercio', 'Fondo de comercio'), ('edificio', 'Edificio'), ('cochera', 'Cochera'), ('otros', 'Otros')], default='otros', max_length=85),
        ),
    ]
