# Generated by Django 4.2.9 on 2024-04-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_alter_property_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='estates.feature'),
        ),
    ]
