# Generated by Django 4.2.9 on 2024-02-08 15:06

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(blank=True, max_length=600, null=True, upload_to=apps.users.models.user_directory),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=600, null=True, upload_to=apps.users.models.user_directory),
        ),
    ]
