# Generated by Django 4.2.9 on 2024-03-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_property_antiquity_alter_property_type'),
        ('users', '0004_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='estates.property'),
        ),
    ]
