# Generated by Django 4.2.9 on 2024-03-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_property_antiquity_alter_property_type'),
        ('users', '0005_alter_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_posts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='estates.property'),
        ),
    ]
